### PR TITLE
My_First_Contribution

### PR DESCRIPTION
**Pull request by Abhinavrajsrivastav**
- Place: Ghaziabad, India
- Bio: College Student | Software Engineer aspirant 
- GitHub: [Abhinav Srivastav](https://github.com/Abhinavrajsrivastav/)

### CODE REVIEW

**Comment by SyedImtiyaz-1** [comment]
Hello @Abhinavrajsrivastav ,
Please add new feature or fix some issue and then add CONTRIBUTING.md so this will better for you profile too.

**Comment by SyedImtiyaz-1** [comment]
Great @Abhinavrajsrivastav 🚀

**Comment by SyedImtiyaz-1** [comment]
@Abhinavrajsrivastav Please add add project details in json file so that it can render on UI

**Comment by SyedImtiyaz-1** [comment]
I reverted the PR please create new and add json too.

**Comment by Abhinavrajsrivastav** [comment]
@SyedImtiyaz-1 sir , what I have to do now ? I have made a pull request and Requested to merge it with the main branch.

**Comment by SyedImtiyaz-1** [comment]
Sure, once your added project is visible then raise a PR.

**Pull request merged**
